# Generated by Django 3.2.9 on 2021-11-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_remove_pin_saved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='pins', to='pins.Topic'),
        ),
    ]
