# Generated by Django 3.2.9 on 2021-11-22 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='saved_by',
        ),
    ]
