# Generated by Django 3.2.9 on 2021-11-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.ManyToManyField(to='pins.Topic'),
        ),
    ]
