# Generated by Django 3.2.9 on 2021-11-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_remove_pin_saved_by'),
        ('accounts', '0004_alter_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_pins',
            field=models.ManyToManyField(blank=True, related_name='saved_by', through='pins.Save', to='pins.Pin'),
        ),
    ]
