# Generated by Django 3.2.9 on 2021-12-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_saved_pins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='profilePic/defaultuser.png', null=True, upload_to='profilePic/%y/%m/%d'),
        ),
    ]
